In [3]:
print('good morning')

good morning


In [4]:
print('good night')

good night


In [5]:
import numpy as np

In [6]:
pointers = [1, 3, 3, 5, 10, 10, 9, 8]

In [11]:
n1 = np.array(pointers, dtype=np.int16)
print(n1)
print(type(n1))
print(n1.shape)
print(n1.ndim)
print(n1.dtype)

[ 1  3  3  5 10 10  9  8]
<class 'numpy.ndarray'>
(8,)
1
int16


In [14]:
# vectorized operations
deducted_marks = n1 - 1
print(deducted_marks)
print(n1 ** 2)

[0 2 2 4 9 9 8 7]
[  1   9   9  25 100 100  81  64]


In [20]:
# filtering
print(n1)
morethan5 = n1[n1 > 5]
print(morethan5)
odd_pointers = n1[(n1 % 2 != 0) & (n1 < 5)]
print(odd_pointers)

[ 1  3  3  5 10 10  9  8]
[10 10  9  8]
[1 3 3]


In [24]:
# indexing
print(n1)
print(n1[0])
print(n1[-1])
print(n1[[0, -1]])

[ 1  3  3  5 10 10  9  8]
1
8
[1 8]


In [27]:
# slicing
print(n1)
print(n1[:3])
print(n1[-3:])

[ 1  3  3  5 10 10  9  8]
[1 3 3]
[10  9  8]


In [30]:
# indexing + assignment
print(n1)
n1[-1] = 9
print(n1)
n1[[1, -2]] = [9, 10]
print(n1)

[ 1  3  3  5 10 10  9  9]
[ 1  3  3  5 10 10  9  9]
[ 1  9  3  5 10 10 10  9]


In [33]:
# slicing + assignment
print(n1)
n1[:3] = [4, 4, 10]
print(n1)

[ 1  9  3  5 10 10 10  9]
[ 4  4 10  5 10 10 10  9]


In [40]:
# aggregation functions
print(n1)
print(n1.max())
print(n1.min())
print(n1.mean())
print(n1.std())
print(n1.var())
print(n1.cumsum())

[ 4  4 10  5 10 10 10  9]
10
4
7.75
2.680951323690902
7.1875
[ 4  8 18 23 33 43 53 62]


In [42]:
print(n1)
weighted_ar = np.where(n1 > 5, 1, 0)
print(weighted_ar)

[ 4  4 10  5 10 10 10  9]
[0 0 1 0 1 1 1 1]


In [44]:
n1.sort()
print(n1)

[ 4  4  5  9 10 10 10 10]
