In [8]:
import numpy as np
import numpy.random as rd

In [5]:
print(np.zeros(10))
print(np.ones(20))
print(np.arange(21))
print(np.arange(11, 31))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]


In [7]:
print(np.zeros((3, 3)))
print(np.identity(3))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
print(rd.normal(size=10))
print(rd.normal(size=(3,3)))

[ 0.29980438 -0.67637226  1.45758224 -1.47715297 -0.3035891  -1.16202859
  0.40560303  0.53197934  0.07814089  0.46600733]
[[-0.11134151 -0.96610454  0.93940724]
 [ 0.09286169 -1.49768663  0.11856689]
 [ 1.00780145 -0.1641364  -0.01146357]]
