In [1]:
import numpy as np

In [2]:
pcm = [
    [93, 99, 100],
    [92, 80, 56],
    [89, 89, 45]
]

In [5]:
n1 = np.array(pcm, dtype=np.int16)
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 93  99 100]
 [ 92  80  56]
 [ 89  89  45]]
<class 'numpy.ndarray'>
2
(3, 3)


In [12]:
print(n1)
# indexing
print(n1[0])
print(n1[-1])
print(n1[[0, -1]])
print(n1[-1][-1]) # not so effecient in numpy
print(n1[-1, -1]) # much more optimized and preferred in numpy

[[ 93  99 100]
 [ 92  80  56]
 [ 89  89  45]]
[ 93  99 100]
[89 89 45]
[[ 93  99 100]
 [ 89  89  45]]
45
45


In [15]:
print(n1)
deducted_marks = n1 - [1, 0, 2]
print(deducted_marks) # broadcasting

[[ 93  99 100]
 [ 92  80  56]
 [ 89  89  45]]
[[92 99 98]
 [91 80 54]
 [88 89 43]]


In [19]:
print(n1)
n2 = n1 - [
    [1, 0, 0],
    [0, 0, 0],
    [2, 0, 0]
]
print(n2) # broadcasting

[[ 93  99 100]
 [ 92  80  56]
 [ 89  89  45]]
[[ 92  99 100]
 [ 92  80  56]
 [ 87  89  45]]


In [22]:
# aggregation
print(n1)
print(n1.sum(axis=1))
print(n1.mean(axis=0))

[[ 93  99 100]
 [ 92  80  56]
 [ 89  89  45]]
[292 228 223]
[91.33333333 89.33333333 67.        ]


In [23]:
n3 = np.array([
    [10, 10, 4],
    [9, 6, 10],
    [9, 10, 1]
])
print(n3)

[[10 10  4]
 [ 9  6 10]
 [ 9 10  1]]


In [25]:
n3.flatten().mean()

7.666666666666667